const COLUMNS = {
    ACCOUNT_NUMBER: 138, // Default
    ACCOUNT_NAME: 139, // Default
    ENTRY_FACILITY_SHIP_FROM_ZIP: 140,
    MANIFEST_DATE_YEARFIRST: 141, // YYYY-MM-DD
    SHIP_TO_ZIP: 144,
    POSTAL_CLASS: 145, // Default (Service Name)
    TRAILER_NUMBER: 147, // Default
    ACTUAL_WEIGHT: 148, // Default
    DELIVERY_CONF_FREE: 153,
    SIGNATURE_FEE: 154, // Default
    ADDRESS_CORRECTION_FEE: 155, // Default
    SPECIAL_HANDLING_FEE: 156, // Default
    MISC_FEE: 157, // Default
    BILL_ZONE: 162, // Default
    POSTAGE_TOTAL: 163, // Default
    SERVICE_CHARGES: 164, // Default
    FUEL_SURCHARGE: 165, // Default
    TOTAL_FEE: 166, // Default
    TRACKING_NUMBER: 173, // Default
    REFERENCE_NUMBER: 177, // Default
    MANIFEST_DATE_YEARLAST: 183, // MM/DD/YYYY
    RATED_DATE: 184, // Default
    USPS_BARCODE: 185, // Default
    INDUCTION_FACILITY_ZIP: 198, // Default
    ADDLREF1: 203, // Default
    DIM_WEIGHT_FEE: 2031, // Default
    BALLOON_FEE: 2033, // Default
    OVERSIZE_FEE: 2034, // Default
    NONMACHINABLE_FEE: 2035, // Default
    DELIVERY_EXCEPTION_FEE: 2036, // Default
    MANIFEST_DATE: 2051, // Default
    SHIP_FROM_ZIP: 2052, // Default
    VOLUME_ADJUSTMENT_FEE: 2055, // Default
    NON_CONTINENTAL_FEE: 2059, // Default
    TRANSPORTATION_FEE_AMT: 2238,
    APOFPO_ZIP_FLAG: 2240,
    INDUCTION_FACILITY: 2314,
    PRIMARY_BARCODE_ORIGINAL: 2322,
    ORIGINAL_PRIMARY_BARCODE: 2323, // Default
    REFERENCE_NUMBER_ORIGINAL: 2324,
    WIDTH: 2326, // Default
    LENGTH: 2327, // Default
    HEIGHT: 2328, // Default
    DIM_WEIGHT: 2329 // Default
}

module.exports = {
    COLUMNS
}