import { Oracle } from './oracle.js'
import { RequestValidator } from './requestvalidator.js'
import { COLUMNS } from './columns.js'

var request = {
  desiredFields: [
    COLUMNS.REFERENCE_NUMBER,
    COLUMNS.BALLOON_FEE,
    COLUMNS.OVERSIZE_FEE,
    COLUMNS.NONMACHINABLE_FEE,
    COLUMNS.VOLUME_ADJUSTMENT_FEE,
    COLUMNS.TRANSPORTATION_FEE_AMT,
    COLUMNS.ORIGINAL_PRIMARY_BARCODE,
    COLUMNS.APOFPO_ZIP_FLAG
  ],
  merchantName: "E-Fashion E-Commerce",
  merchantID: 2976,
  ticketNumber: 17728,
  saveLocation: 'C:\\Users\\be016sa\\Documents\\ngs_bill_database_oracle_newg\\scripts',
  newBEF: false,
  customDate: '01-NOV-2019',
  defaultBEF: false,
  invoice_class: 'FORWARD',
  addDelete: false
}

function run() {
  if (RequestValidator.prototype.checkRequest(request)) {
    Oracle.prototype.initializeScript(request)
  }
}

run();


//DEFAULT BEF
// COLUMNS.ACCOUNT_NUMBER,
// COLUMNS.ACCOUNT_NAME,
// COLUMNS.MANIFEST_DATE,
// COLUMNS.RATED_DATE,
// COLUMNS.ORIGINAL_PRIMAY_BARCODE,
// COLUMNS.USPS_BARCODE,
// COLUMNS.TRACKING_NUMBER,
// COLUMNS.REFERENCE_NUMBER,
// COLUMNS.ADDLREF1,
// //COLUMNS.ADDLREF2,
// COLUMNS.SHIP_FROM_ZIP,
// COLUMNS.SHIP_TO_ZIP,
// COLUMNS.INDUCTION_FACILITY_ZIP,
// COLUMNS.POSTAGE_CLASS,
// COLUMNS.TRAILER_NUMBER,
// COLUMNS.ACTUAL_WEIGHT,
// COLUMNS.WIDTH,
// COLUMNS.HEIGHT,
// COLUMNS.LENGTH,
// COLUMNS.DIM_WEIGHT,
// COLUMNS.BILL_ZONE,
// COLUMNS.DELIVERY_CONF_FREE,
// COLUMNS.BALLOON_FEE,
// COLUMNS.SIGNATURE_FEE,
// COLUMNS.ADDRESS_CORRECTION_FEE,
// COLUMNS.DIM_WEIGHT_FEE,
// COLUMNS.OVERSIZE_FEE,
// COLUMNS.NONMACHINABLE_FEE,
// COLUMNS.NON_CONTINENTAL_FEE,
// COLUMNS.SPECIAL_HANDLING_FEE,
// COLUMNS.DELIVERY_EXCEPTION_FEE,
// COLUMNS.VOLUME_ADJUSTMENT_FEE,
// COLUMNS.MISC_FEE,
// COLUMNS.POSTAGE_TOTAL,
// COLUMNS.SERVICE_CHARGES,
// COLUMNS.FUEL_SURCHARGE,
// COLUMNS.TOTAL_FEE